[Scripts] Check time against U.S. Naval Observatory if possible
At FPP startup, if machine is internet connected, check time against
the U.S. Naval Observatory via HTTP in case NTP is blocked/disabled.
If local time appears sane, nothing is done.  If local time is off by
more than 24 hours, set local time to time from USNO.

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -563,3 +563,43 @@ detectFalconHardware() {
 	fi
 }
 
+#############################################################################
+# Check local time against U.S. Naval Observatory time, set if too far out
+checkTimeAgainstUSNO () {
+	# www.usno.navy.mil is not pingable, so check github.com instead
+	ping -q -c 1 github.com > /dev/null 2>&1
+
+	if [ $? -eq 0 ]
+	then
+		echo "FPP: Checking local time against U.S. Naval Observatory"
+
+		# allow clocks to differ by 24 hours to handle time zone differences
+		THRESHOLD=86400
+		USNOSECS=$(curl -s http://www.usno.navy.mil/cgi-bin/time.pl | sed -e "s/.*\">//" -e "s/<\/t.*//" -e "s/...$//")
+		LOCALSECS=$(date +%s)
+		MINALLOW=$(expr ${USNOSECS} - ${THRESHOLD})
+		MAXALLOW=$(expr ${USNOSECS} + ${THRESHOLD})
+
+		#echo "FPP: USNO Secs  : ${USNOSECS}"
+		#echo "FPP: Local Secs : ${LOCALSECS}"
+		#echo "FPP: Min Valid  : ${MINALLOW}"
+		#echo "FPP: Max Valid  : ${MAXALLOW}"
+
+		echo "FPP: USNO Time  : $(date --date=@${USNOSECS})"
+		echo "FPP: Local Time : $(date --date=@${LOCALSECS})"
+
+		if [ ${LOCALSECS} -gt ${MAXALLOW} -o ${LOCALSECS} -lt ${MINALLOW} ]
+		then
+			echo "FPP: Local Time is not within 24 hours of USNO time, setting to USNO time"
+			date $(date --date="@${USNOSECS}" +%m%d%H%M%Y.%S)
+
+			LOCALSECS=$(date +%s)
+			echo "FPP: New Local Time: $(date --date=@${LOCALSECS})"
+		else
+			echo "FPP: Local Time is OK"
+		fi
+	else
+		echo "FPP: Not online, unable to check time against U.S. Naval Observatory."
+	fi
+}
+
