Fix Internet Health check
As per https://github.com/fail2ban/fail2ban/issues/313, example.com has moved
and the old ip address stopped responding.  Changed to use the ip address of
fppstatus because that same server is also used for checking for available updates.  Has to be an IP address because DNS may not be configured.

Also add a backup server to check (kulplights.com) but only if the first
server doesn't respond.

Closes #2176

diff --git a/scripts/healthCheck b/scripts/healthCheck
--- a/scripts/healthCheck
+++ b/scripts/healthCheck
@@ -202,8 +202,15 @@ HC_PingGateway() {
 HC_Internet() {
     PrintItemHead "Internet Access"
 
-    curl http://192.0.43.10 --max-time 2 > /dev/null 2>&1 #this checks the iana example.com
-    if [ $? -eq 0 ]
+    curl http://50.116.60.82 --max-time 2 > /dev/null 2>&1 #this checks fppstats.falconchristmas.com
+    rc=$?
+    # If first check fails, then use backup.
+    if [ $rc -ne 0 ]; then
+        curl http://216.40.34.37 --max-time 2 > /dev/null 2>&1 #this checks kulp.com
+        rc=$?
+    fi
+
+    if [ $rc -eq 0 ]
     then
         STATUS=1
         STATUSSTR="Internet connectivity confirmed."
